#!/bin/bash

me=$(basename $0)

usage="

NAME
  ${me} - computes the power set of a set.

SYNOPSIS
  ${me} [OPTIONS] datafile
  ${me} < datafile
  cat datafile | ${me} 

DESCRIPTION
  ${me} reads one element per line of stdin and then outputs on stdout the
  power set.

OPTIONS
  -h  Displays help message.

  -v  Increase verbosity.

AUTHOR
  Berend M. Tober

"

n=0
tmpfile=".${me}.$$"
trap 'rm "${tmpfile}"' EXIT
touch "${tmpfile}"

infile="-"
unset verbose

while [[ $# -gt 0 ]]
do
  case "${1}" in
    -h)
      echo "${usage}"
      exit
      ;;
    -v)
      verbose=true
      ;;
    -*)
      echo "Invalid option '${1}'"
      exit
      ;;
    *)
      infile="${1--}"
      shift 1
      ;;
  esac
  shift
done  

[ -n "${verbose}" ] && echo "==> powerset(${infile}) <=="
cat "${infile}" | while read f
do
  cat "${tmpfile}" | while read g
  do
    echo -e "${f}\t${g}" | tee -a "${tmpfile}"
  done

  echo "${f}" | tee -a "${tmpfile}"
done
echo ""

